// protoc --go_out=. --go-grpc_out=. ./*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: msg_id.proto

package pbcli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// must: all rsp is req id+1, req is even, rsp is odd
type Msg int32

const (
	Msg_Id_Nonsense     Msg = 0
	Msg_Id_HeartBeatReq Msg = 2
	Msg_Id_LoginReq     Msg = 4
	Msg_Id_ErrorNtf     Msg = 65535
)

// Enum value maps for Msg.
var (
	Msg_name = map[int32]string{
		0:     "Id_Nonsense",
		2:     "Id_HeartBeatReq",
		4:     "Id_LoginReq",
		65535: "Id_ErrorNtf",
	}
	Msg_value = map[string]int32{
		"Id_Nonsense":     0,
		"Id_HeartBeatReq": 2,
		"Id_LoginReq":     4,
		"Id_ErrorNtf":     65535,
	}
)

func (x Msg) Enum() *Msg {
	p := new(Msg)
	*p = x
	return p
}

func (x Msg) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_id_proto_enumTypes[0].Descriptor()
}

func (Msg) Type() protoreflect.EnumType {
	return &file_msg_id_proto_enumTypes[0]
}

func (x Msg) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg.Descriptor instead.
func (Msg) EnumDescriptor() ([]byte, []int) {
	return file_msg_id_proto_rawDescGZIP(), []int{0}
}

var File_msg_id_proto protoreflect.FileDescriptor

var file_msg_id_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x62, 0x63, 0x6c, 0x69, 0x2a, 0x4f, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0f, 0x0a, 0x0b,
	0x49, 0x64, 0x5f, 0x4e, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x65, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x49, 0x64, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x64, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0b, 0x49, 0x64, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4e,
	0x74, 0x66, 0x10, 0xff, 0xff, 0x03, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x62, 0x63, 0x6c,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_id_proto_rawDescOnce sync.Once
	file_msg_id_proto_rawDescData = file_msg_id_proto_rawDesc
)

func file_msg_id_proto_rawDescGZIP() []byte {
	file_msg_id_proto_rawDescOnce.Do(func() {
		file_msg_id_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_id_proto_rawDescData)
	})
	return file_msg_id_proto_rawDescData
}

var file_msg_id_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_id_proto_goTypes = []interface{}{
	(Msg)(0), // 0: pbcli.msg
}
var file_msg_id_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msg_id_proto_init() }
func file_msg_id_proto_init() {
	if File_msg_id_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_id_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_id_proto_goTypes,
		DependencyIndexes: file_msg_id_proto_depIdxs,
		EnumInfos:         file_msg_id_proto_enumTypes,
	}.Build()
	File_msg_id_proto = out.File
	file_msg_id_proto_rawDesc = nil
	file_msg_id_proto_goTypes = nil
	file_msg_id_proto_depIdxs = nil
}
